### PR TITLE
Configurable checkout success page url

### PR DESCRIPTION
**Pull request by magextrem**
Hi there,

This is a feature to be able to configure checkout success page for each hipay payment mode.
We had to develop this because we use a custom checkout and not the default onepage, so success page url isn't "checkout/onepage/success".

### CODE REVIEW

**Comment by jprotin** [comment]
Hi kthomas59,

Thank you for your contribution !

Can you modify your pull-request and associate it with the develop branch ?

Thank you

Johan.

**Comment by magextrem** [comment]
Hi Johan,

Thanks for replying quickly :)

I've just associated the PR with hipay:develop branch, is it ok ?

Thanks,

Kevin

**Comment by jprotin** [comment]
Hi Kevin,

It's ok, i check and test your pull-request as fast as possible :) !

Thank you,

Johan

**Comment by magextrem** [comment]
Thanks,

Let me know if you notice any bug ;)

Kevin

**Review by jprotin — APPROVED** [review]

**Pull request merged**
